#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : xrestop
Version  : 0.4
Release  : 4
URL      : http://downloads.yoctoproject.org/releases/xrestop/xrestop-0.4.tar.gz
Source0  : http://downloads.yoctoproject.org/releases/xrestop/xrestop-0.4.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: xrestop-bin
Requires: xrestop-doc
BuildRequires : ncurses-dev
BuildRequires : pkgconfig(ncurses)
BuildRequires : pkgconfig(x11)
BuildRequires : pkgconfig(xext)
BuildRequires : pkgconfig(xres)

%description
XResTop is A 'top' like tool for monitoring X Client server resource usage.
It requires the XRes extension.

%package bin
Summary: bin components for the xrestop package.
Group: Binaries

%description bin
bin components for the xrestop package.


%package doc
Summary: doc components for the xrestop package.
Group: Documentation

%description doc
doc components for the xrestop package.


%prep
%setup -q -n xrestop-0.4

%build
export LANG=C
%configure --disable-static
make V=1  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/xrestop

%files doc
%defattr(-,root,root,-)
%doc /usr/share/man/man1/*
